# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandreroulin/work/nibbler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandreroulin/work/nibbler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/alexandreroulin/work/nibbler && $(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandreroulin/work/nibbler/CMakeFiles /Users/alexandreroulin/work/nibbler/extern/KStar/CMakeFiles/progress.marks
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f CMakeFiles/Makefile2 extern/KStar/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandreroulin/work/nibbler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f CMakeFiles/Makefile2 extern/KStar/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f CMakeFiles/Makefile2 extern/KStar/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f CMakeFiles/Makefile2 extern/KStar/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/alexandreroulin/work/nibbler && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
extern/KStar/CMakeFiles/KStar.dir/rule:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f CMakeFiles/Makefile2 extern/KStar/CMakeFiles/KStar.dir/rule
.PHONY : extern/KStar/CMakeFiles/KStar.dir/rule

# Convenience name for target.
KStar: extern/KStar/CMakeFiles/KStar.dir/rule

.PHONY : KStar

# fast build rule for target.
KStar/fast:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f extern/KStar/CMakeFiles/KStar.dir/build.make extern/KStar/CMakeFiles/KStar.dir/build
.PHONY : KStar/fast

KStar.o: KStar.cpp.o

.PHONY : KStar.o

# target to build an object file
KStar.cpp.o:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f extern/KStar/CMakeFiles/KStar.dir/build.make extern/KStar/CMakeFiles/KStar.dir/KStar.cpp.o
.PHONY : KStar.cpp.o

KStar.i: KStar.cpp.i

.PHONY : KStar.i

# target to preprocess a source file
KStar.cpp.i:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f extern/KStar/CMakeFiles/KStar.dir/build.make extern/KStar/CMakeFiles/KStar.dir/KStar.cpp.i
.PHONY : KStar.cpp.i

KStar.s: KStar.cpp.s

.PHONY : KStar.s

# target to generate assembly for a file
KStar.cpp.s:
	cd /Users/alexandreroulin/work/nibbler && $(MAKE) -f extern/KStar/CMakeFiles/KStar.dir/build.make extern/KStar/CMakeFiles/KStar.dir/KStar.cpp.s
.PHONY : KStar.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... KStar"
	@echo "... KStar.o"
	@echo "... KStar.i"
	@echo "... KStar.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/alexandreroulin/work/nibbler && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

